config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'challenges#new'

  get '/about', to: 'pages#about'

  resource :dashboard, only: [:show]

  resources :challenges, except: [:index] do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :checkpoints, only: [:index]
    resources :logged_times, only: [:new, :create]
    
    member do
      get :preview
      patch :accept
      patch :decline
      patch :concede
    end
  end
end

app/models/logged_time.rb
class LoggedTime < ActiveRecord::Base
  belongs_to :challenge
  belongs_to :user

  scope :between, -> (start_date, end_date) do 
    where("DATE(created_at) >= :start_date AND DATE(created_at) <= :end_date", start_date: start_date, end_date: end_date)
  end
end

app/controllers/logged_times_controller.rb
class LoggedTimesController < ApplicationController
  before_action :set_challenge

  def new
  end

  def create
    amount = params[:amount]
    LoggedTime.create!(challenge: @challenge, user: current_user, amount: amount)
  end

  private

  def set_challenge
    @challenge = current_user.all_challenges.find(params[:challenge_id])
    @challenge_decorator = ChallengeDecorator.decorate(@challenge)
  end
end

app/views/logged_times/_form.html.erb
  <!-- complete wrapper for logged_times -->
  <div id="logging-form" data-url="<%= challenge_logged_times_path(challenge) %>">
    <!-- wrapper for logging times -->
    <div class="wrapper-logging-times">
      <div class="wrapper-log-hours">
        <div class="add-hours-container">
          <div id="addhours" class="log-button">
            +
          </div>
        </div>
        <div class="hour-container">
          <div class="hour-text">
            <span id="hour">0</span><span class="hour-label">h</span>
          </div>
        </div>
        <div class="remove-hours-container">
          <div id="removehours" class="log-button">
            -
          </div>
        </div>
      </div>
      <div class="seperator">
        :
      </div>
      <div class="wrapper-log-minutes">
        <div class="add-minutes-container">
         <div id="addminutes" class="log-button">
          +
        </div>
      </div>
      <div class="minute-container">
        <div class="minute-text">
          <span id="minute">00</span><span class="minute-label">min</span>
        </div>
      </div>
      <div class="remove-minutes-container">

        <div id="removeminutes" class="log-button">
          -
        </div>
      </div>

    </div> 
  </div>
  <!-- button logging hours -->
  <div class="button-logging-hours-container">    
    <div class="button-logging-hours">
      SAVE
    </div>
  </div>
</div>

app/views/logged_times/create.js.erb
$(".whoop-container").removeClass('is-open');
$('.challenge-container').html("<%= j render "challenges/challenge", challenge: @challenge, challenge_decorator: @challenge_decorator %>");

app/views/logged_times/new.html.erb
<%= render "form", challenge: @challenge %>