config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'challenges#new'

  get '/about', to: 'pages#about'

  resource :dashboard, only: [:show]

  resources :challenges, except: [:index] do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :checkpoints, only: [:index]
    resources :logged_times, only: [:new, :create]
    
    member do
      get :preview
      patch :accept
      patch :decline
      patch :concede
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_meta.html.erb
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= image_url(meta_image) %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="<%= DEFAULT_META[:twitter_account] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META[:twitter_account] %>">
<meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

<!-- Google+ Schema.org markup -->
<meta itemprop="name" content="<%= meta_title %>">
<meta itemprop="description" content="<%= meta_description %>">
<meta itemprop="image" content="<%= image_url(meta_image) %>">

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "chicken.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">


    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if params[:action] == "show" && params[:controller] == "challenges" && @challenge.status != "pending" %>
        <i class="fa fa-bars fa-2x dropdown-toggle yellow_dropdown" data-toggle="dropdown"></i>
        <% else %>
        <i class="fa fa-bars fa-2x dropdown-toggle white_dropdown" data-toggle="dropdown"></i>
        <% end %>
<!--         <div class="badge badge-yellow">3</div>
 -->        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <!-- Different navigation if login or not -->
          <% if user_signed_in? %>

          <!-- Notification -->
          <li><%= link_to dashboard_path , class: "navbar-wagon-item" do %>
            <i class="fa fa-dashboard"></i>  <%= t ".top_call_to_action", default: "Dashboard" %>
          <% end %>
          </li>
          <li><%= link_to about_path, class: "navbar-wagon-item" do %>
                <i class="fa fa-info-circle"></i>  <%= t ".top_call_to_action", default: "About" %>
              <% end %>
          </li>
          <!-- Do we need this? -->
         <!--  <li><%#= link_to t(".top_call_to_action", default: "Rules"), "#", class: "navbar-wagon-item" %>
          </li>
          <li><%#= link_to t(".top_call_to_action", default: "Contact us"), "#", class: "navbar-wagon-item" %>
          </li> -->

          <!-- Profile picture and dropdown -->
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>

          <% else %>

          <!-- Login text link -->
          <%= link_to new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-sign-in"></i>  <%= t ".sign_in", default: "Log in" %>
          <% end %>

          <% end %>
        </div>

        <!-- Dropdown list appearing on mobile only -->
      </ul>
    </div>
  </div>
</div>