config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'challenges#new'

  get '/about', to: 'pages#about'

  resource :dashboard, only: [:show]

  resources :challenges, except: [:index] do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :checkpoints, only: [:index]
    resources :logged_times, only: [:new, :create]
    
    member do
      get :preview
      patch :accept
      patch :decline
      patch :concede
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    set_challenges_current_user
    set_logged_times_current_user
  end

  private

  def set_challenges_current_user
    @challenges = ChallengeDecorator.decorate_collection(current_user.all_challenges)
  end

  def set_logged_times_current_user
    @sum_logged_times = current_user.logged_times.sum(:amount) / 60
  end
end

app/views/dashboards/show.html.erb
<div class="dashboard">
  <div class="page_title">
    <h1>
      Dashboard
    </h1>
  </div>
  <div class="user_info">
    <div class="user_photo">
      <%= image_tag current_user.picture, class:"avatar avatar_dashboard" %>
    </div>
    <div class="challenges_amount">
      <p>
        <i class="fa fa-flag"></i> <%= "#{@challenges.count}" %> 
      </p>
   
    </div>
  </div>

  <% @challenges.reverse_each do |challenge| %>
    <div class="index-challenge-card">
      <div class="challenge-specs">
        <div class="challenge_date">
          <% if challenge.ongoing? %>
          <p><%= challenge.days_left %>   <i class="fa fa-calendar-plus-o"></i> </p>
          <% elsif challenge.finished? %>
          <p>Finished!</p>
          <% else %>
          <p>Not yet started</p>
          <% end %>

        </div>
        <% if challenge.opponent(current_user) %>
        <%= image_tag challenge.opponent(current_user).picture, class: "avatar-small card-user" %>
        <% else %>
        <%= image_tag "default.png", class: "avatar-small card-user" %>
        <% end %>
        <p><%= challenge.name_challenger %></i></span></p>
      </div>


      <div class="challenge_info">
        <div class="activity_name">
          <%= link_to challenge.activity, challenge_path(challenge) %>
          <% if challenge.winner_user?(current_user) %>
          <span><i class="fa fa-trophy"></i></span>
          <% end %>
        </div>
      </div>
      <div class="status">
        <p>
          <% if challenge.status == "accepted" %>
          <p> </p>
          <% elsif challenge.status == "pending" %>
          <p>Pending...</p>
          <% end %>
        </p> 
        <% if challenge.status == "pending" %>
        <p></p>
        <% elsif challenge.status == "accepted" && challenge.ongoing? %>
        <%= link_to concede_challenge_path(challenge), method: :patch,data: { confirm: "Are you sure you want to chicken out?"} do %>
        <p class="concede">Give up?</p>
        <% end %>
        <% else %>
        <%= link_to challenge_path(challenge), method: :delete, data: { confirm: "Are you sure you want to delete this challenge from your list?"} do %>
        <p class="concede">Delete</p>
        <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>