config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'challenges#new'

  get '/about', to: 'pages#about'

  resource :dashboard, only: [:show]

  resources :challenges, except: [:index] do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :checkpoints, only: [:index]
    resources :logged_times, only: [:new, :create]
    
    member do
      get :preview
      patch :accept
      patch :decline
      patch :concede
    end
  end
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :creator, class_name: "User" #, foreign_key: "creator_id"
  belongs_to :challenger, class_name: "User" #, foreign_key: "challenger_id"
  has_many :messages, dependent: :destroy
  has_many :checkpoints, dependent: :destroy
  has_many :logged_times, dependent: :destroy

  validates :name_challenger, presence: true, on: :update
  validates :activity, presence: true, on: :update
  validates :email_challenger, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
    message: "that is not an email address!" }, on: :update
  validates :allotment, format: { with: /\A[+-]?\d+\Z/,
    message: "that is not a correct number of hours" }, on: :update
  validates :start_date, presence: true, on: :update
  validates :wager_description, presence: true, on: :update
  validates :wager_amount, presence: true, format: { with: /\A[+-]?\d+\Z/,
    message: "don't forget to fill in the wager!" },  on: :update
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :preview, :accept, :decline]

  before_action :set_challenge_by_token, only: [:preview, :accept, :decline]
  before_action :set_challenge, only: [:edit, :show, :update, :destroy, :concede]
  before_action :check_challenger_not_set, only: [:accept, :decline]
  
  def preview
  end

  def show 
    check_checkpoints
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params_new)
    @challenge.token = SecureRandom.hex(13)

    if user_signed_in?
      create_with_user
    else
      create_without_user
    end
  end

  def edit
  end

  def update
    @challenge.assign_attributes(challenge_params_edit)
    @challenge.deadline = @challenge.start_date + 4.weeks

    if @challenge.save 
      flash[:notice] = "Succesfully created this challenge"
      UserMailer.welcome_email(@challenge).deliver_now

      redirect_to challenge_path
    else
      flash.now[:alert] = "Oops.. Let's try again"
      render :edit
    end
  end

  def destroy
    @challenge.destroy
    redirect_to dashboard_path
  end

  def accept 
    if user_signed_in?
      accept_with_user
    else
      accept_without_user
    end
  end

  def decline
    @challenge.update(status: :declined)
    flash[:notice] = "Successfully declined. Thanks."

    if user_signed_in?
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def concede
    @challenge.update(status: :conceded)
    flash[:notice] = "Successfully conceded, Chicken!"
    redirect_to dashboard_path
  end

  private

  def accept_with_user
    @challenge.status = :accepted
    @challenge.challenger = current_user
    @challenge.save

    flash[:notice] = "Welcome to this challenge!"
    redirect_to challenge_path(@challenge)
  end

  def accept_without_user
    session[:challenge_to_accept] = @challenge.id
    redirect_to user_omniauth_authorize_path(:facebook)
  end

  def challenge_params_new
    params.require(:challenge).permit(:activity, :email_challenger, :wager_amount)
  end

  def challenge_params_edit
    params.require(:challenge).permit(:activity, :email_challenger, :name_challenger, :wager_amount, :wager_description, :start_date, :deadline, :allotment)
  end

  def create_with_user
    @challenge.creator = current_user

    if @challenge.save
      redirect_to edit_challenge_path(@challenge)
    else
      flash[:alert] = "You haven't filled out the boxes correctly"
      render :new
    end
  end

  def create_without_user
    if @challenge.valid?
      session[:new_challenge] = challenge_params_new.to_hash
      redirect_to new_user_session_path
    else
      flash[:alert] = "You haven't filled out the boxes correctly"
      render :new
    end
  end

  def set_challenge
    @challenge = Challenge.find(params[:id])
    @challenge_decorator = ChallengeDecorator.decorate(@challenge)
  end

  def set_challenge_by_token
    @challenge = Challenge.where(status: "pending", token: params[:id]).first

    unless @challenge
      flash[:alert] = "Don't know what you're talking about"
      redirect_to root_path
    end
  end

  def check_challenger_not_set
    if @challenge.challenger
      flash[:alert] = "This challenge is already accepted!"
      redirect_to challenge_path(@challenge)
    end
  end

  def check_checkpoints
    Checkpoints::CheckService.new(@challenge, @challenge_decorator.current_week).call
  end
end

app/views/challenges/_challenge.html.erb
<div class="challenge_status">
  <div class="avatarbox">
    <%= image_tag challenge.creator.picture, class: "avatar avatar_shadow box-item creator " %>
    <% if challenge.challenger %>
      <%= image_tag challenge.challenger.picture, class: "avatar avatar_shadow box-item challenger " %>
    <% else %>
      <%= image_tag "http://static1.squarespace.com/static/55b0eea6e4b0eac970b56fa2/t/567c8e6de0327cd48acb8afe/1451003519533/chicken-sombrero.gif", class: "avatar box-item challenger" %>
    <% end %>
  </div>
  <% if challenge_decorator.winner %>
    <%= render "challenges/winner_names", challenge_decorator: @challenge_decorator, challenge: @challenge %>
  <% else %>
    <%= render "challenges/no_winner_names", challenge_decorator: @challenge_decorator, challenge: @challenge %>
  <% end %>
</div>
<div class="wagers">
  <div class="wager creator">
    <div class="euro">&#8364;</div>
    <div><%= challenge_decorator.current_amounts[:creator].round %></div>
  </div>
  <div class="wager filler"></div>
  <div class="wager challenger">
    <div class="euro">&#8364;</div>
    <div><%= challenge_decorator.current_amounts[:challenger].round %></div>
  </div>
</div>
<div class="creatorwagerbar" style="width: <%= challenge_decorator.bar_values[:creator] %>%;"></div>
<div class="challengerwagerbar" style="width: <%= challenge_decorator.bar_values[:challenger] %>%;"></div>
<div class="score">
  <h2>score</h2>
  <div class="avatarbox-score allotment">
    <div class="challenge-avatar avatar_shadow" style="<%= "transform: scale(#{challenge_decorator.logged_times_ratios[:creator]}); background: linear-gradient(rgba(236, 105, 101, 0.0), rgba(236, 105, 101, 0.0)), url(#{challenge.creator.picture})" %>">
      <span class="logging-times-avatar">
        <%= challenge_decorator.logged_times_amounts_in_hours[:creator] %><span class="hour-log-label">h <% unless challenge_decorator.logged_times_amounts_plus_minutes[:creator] == 0 %> </span><%= challenge_decorator.logged_times_amounts_plus_minutes[:creator] %><span class="minute-log-label">min</span> <% end %>
      </span>
    </div>
    <div class="alloted"><%= challenge.allotment %></div>
    <!-- If we are up and running: this is not nil can be removed because it will be possible to be seen -->
    <% if challenge.challenger != nil %>
    <div class="challenge-avatar avatar_shadow" style="<%= "transform: scale(#{challenge_decorator.logged_times_ratios[:challenger]}); background: linear-gradient(rgba(22, 83, 161, 0.0), rgba(22, 83, 161, 0.0)), url(#{challenge.challenger.picture})" %>"  >
      <span class="logging-times-avatar">
        <%=  challenge_decorator.logged_times_amounts_in_hours[:challenger] %><span class="hour-log-label">h <% unless challenge_decorator.logged_times_amounts_plus_minutes[:challenger] == 0 %></span><%= challenge_decorator.logged_times_amounts_plus_minutes[:challenge] %><span class="minute-log-label">min</span> <% end %>
      </span>
    </div>
    <% else %>

    <%= image_tag "http://static1.squarespace.com/static/55b0eea6e4b0eac970b56fa2/t/567c8e6de0327cd48acb8afe/1451003519533/chicken-sombrero.gif", class: "avatar-small", style: "transform: scale(#{challenge_decorator.logged_times_ratios[:challenger]})" %>
    <% end %>
  </div>
</div>

app/views/challenges/_no_winner_names.html.erb
<div class="week">
  <% if challenge_decorator.ongoing? %>
    Week <%= challenge_decorator.current_week %>
  <% else %>
    Starting on <%= l(challenge.start_date) %>
  <% end %>
</div>
<h1><%=challenge.activity.upcase%></h1>
<div class="playerbox">
  <p class="player-item"><%= challenge.creator.first_name %></p>
  <p class="player-item grey">vs.</p>
  <p class="player-item">
    <% if challenge.challenger != nil %>
      <%= challenge.challenger.first_name %>
    <% else %>
      <%= challenge.name_challenger %>
    <% end %>
  </p>
</div>

app/views/challenges/_winner_names.html.erb
<div class="week">
  Finished  
</div>
<h1><%=@challenge.activity.upcase%></h1>
<div class="playerbox">

<% case challenge_decorator.winner %>
<% when :creator %>
  <p class="player-item"><span><i class="fa fa-trophy"></i><%= @challenge.creator.first_name %></span></p>
  <p class="player-item grey">vs.</p>
  <p class="player-item"><%= @challenge.challenger.first_name %></p>
<% when :challenger %>
  <p class="player-item"><%= @challenge.creator.first_name %></p>
  <p class="player-item grey">vs.</p>
  <p class="player-item"><span><i class="fa fa-trophy"></i><%= @challenge.challenger.first_name %></span></p>
<% when :tie %>
  <p class="player-item"><span><i class="fa fa-trophy"></i><%= @challenge.creator.first_name %></span></p>
  <p class="player-item grey">vs.</p>
  <p class="player-item"><span><i class="fa fa-trophy"></i><%= @challenge.challenger.first_name %></span></p>
<% end %>
</div>

app/views/challenges/edit.html.erb
  <div class="edit_challenge">
    <h1>Please enter your challenge information!</h1>
    <%=simple_form_for @challenge do |f| %>
    <div  class="edit_container">
    
      <div class="row">
        <div class="col-xs-12 col-md-6 col-lg-offset-3 col-lg-3">
          <p>What do you want to do more often?</p>
        </div>
        <div class="col-xs-12 col-md-6 col-lg-4">
          <%= f.input :activity, placeholder: "hiking", label: false %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-lg-offset-3 col-lg-7">
          <div class="border"></div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-md-6 col-lg-offset-3 col-lg-3">
          <p>How many hours are you planning on doing this per week?</p>
        </div>
        <div class="col-xs-12 col-md-6 col-lg-4">
         <%= f.input :allotment,input_html: { min: '0' }, placeholder: "3 hours", label: false %>
       </div>
     </div>

     <div class="row">
      <div class="col-xs-12 col-lg-offset-3 col-lg-7">
        <div class="border"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-offset-3 col-lg-3">
        <p>Who do you want to do it with?</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= f.input :name_challenger, placeholder: "John", label: false %>
        <%= f.input :email_challenger, placeholder: "yourfriend@email.com", label: false%>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-lg-offset-3 col-lg-7">
        <div class="border"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-offset-3 col-lg-3">
        <p>How confident are you?</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= f.input :wager_amount, input_html: { min: '0', step: 5 }, placeholder: "30 euros", label: false %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-lg-offset-3 col-lg-7">
        <div class="border"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-offset-3 col-lg-3">
        <p>How will you celebrate the end of the challenge?</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= f.input :wager_description, placeholder: "Dinner on 25 december", label: false %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-lg-offset-3 col-lg-7">
        <div class="border"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-offset-3 col-lg-3">
        <p>When do you want to start the challenge?</p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= f.input :start_date, as: :date_picker, :label => 'Date field', label: false %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-lg-offset-3 col-lg-7">
        <div class="border"></div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-offset-3 col-lg-3">
        <p>Your challenge wil be ending on: </p>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <span id='deadline'>Your end-date will display here</span>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-offset-5 col-lg-4">
        <%= f.submit "Create challenge", class:"submit_edit_form", label: false %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/challenges/new.html.erb
<%=simple_form_for @challenge do |f| %>
<div class='questions-container'>
  <div class="question-container" id='next1' data-next='#next2'  >
    <div class="question-content">
      <div>
        <span class="no-highlight">What do</span> you <span class="no-highlight"> want to do </span>more often?        
      </div>
      <div class='question-input-container'>
        <%= f.input :activity, class: "new_challenge_input", placeholder: 'Work out', label: false %>
      </div>
      <div class='question-next-button'>
        <a href='#next2' id="button1" >Ok!</a>
      </div>
    </div>
  </div>
  <div class="question-container" id='next2' data-prev='#next1' data-next='#next3'>
    <div class="question-content">
      <div>
        Who <span class="no-highlight">do you want to challenge to do the same? </span>   
      </div>
      <div class='question-input-container'>
        <%= f.input :email_challenger, class: "new_challenge_input", placeholder: 'yourfriend@email.com', label: false %>
      </div>
      <div class='question-next-button'>
        <a href='#next3' id="button2">Ok!</a>
      </div>
    </div>
  </div>
  <div class="question-container" id='next3' data-prev='#next2' data-next='#summary'>
    <div class="question-content">
      <div>
        How much<span class="no-highlight"> do you dare to bet on</span> succeeding?     
      </div>
      <div class='question-input-container'>
        <%= f.input :wager_amount, class: "new_challenge_input", placeholder: '‎€ 10', label: false %>
      </div>
      <div class='question-next-button'>
        <a href='#summary' id="button3">Ok!</a>
      </div>
    </div>
  </div>
  <div class="question-container" id='summary' data-prev='#next3'>
    <div class="question-content">
      <div class ="summary">
        <p class="p_sum">
          <span class="no-highlight">Are you ready to create your</span> <span id="activity">x</span> <span class="no-highlight"> challenge with</span> <span id="challenger"> x </span><span class="no-highlight"> as your opponent </span> <br>
          <span class="no-highlight">and wager &#8364;</span><span id="wager">x</span>?

        </p>
      </div>
      <div class='question-input-container'>
      </div>
      <div class='question-next-button'>
        <%= f.submit "Let's go for it!", class: "summary_submit" %>
      </div>
    </div>
  </div>
</div>
<% end %> 

<%= content_for :after_js do %>
  <script>
    document.body.addEventListener('touchmove', function(e){ e.preventDefault(); });
  </script>
<% end %>

app/views/challenges/preview.html.erb
<div class="preview_title">
  <h1>You've been challenged!</h1>
</div>
<div class="preview_container">
  <%= image_tag @challenge.creator.picture, class: "avatar avatar_shadow preview_avatar" %>

  <div class="preview_info">
    <p>
      <span><%= @challenge.creator.first_name %></span> 
      challenges you to go
      <span><%=@challenge.activity %></span>
    </p>
    <p>
      <span><%= @challenge.creator.first_name %></span>
      is determined to go 
      <span><%=@challenge.activity %></span> for
      <span> <%= @challenge.allotment %></span> 
      hours a week.
      <span><%= @challenge.creator.first_name %></span> 
      is willing to wager
      <span>&#8364; <%= @challenge.wager_amount %></span>
      that the both of you will be able to keep this up for at least 4 weeks!
    </p>
    <p>
      The challenge will begin on <br>
      <span><%= @challenge.start_date.to_formatted_s(:long_ordinal) %></span>
      and it will end on <br>
      <span><%= @challenge.deadline.to_formatted_s(:long_ordinal) %></span>
    </p>
  </div>

  <div class="state_change">
    <%= link_to accept_challenge_path(@challenge.token), method: :patch, class: "state_accept" do %>
    <i class="positive fa fa-check fa-2x"></i>
    <% end %>
    <%= link_to decline_challenge_path(@challenge.token), method: :patch , class: "state_decline" do %>
    <i class="negative fa fa-times fa-2x"></i>
    <% end %>
  </div>
</div>

app/views/challenges/show.html.erb
<% if @challenge.status == "pending" %>
  <div class="cover_pending"></div>
<% else %>
  <div class="challenge-container"><%# PLEASE DO NOT REMOVE ME: js purpose %>
    <%= render "challenge", challenge: @challenge, challenge_decorator: @challenge_decorator %>
  </div>

  <% if @challenge_decorator.ongoing? %>
    <div class="whoop-container">
      <div class="add_score"><span>+</span></div>
      <%= render "logged_times/form", challenge: @challenge %>
    </div>
  <% end %>
<% end %>